### ISSUE TITLE
Event page map and speakers 

### ISSUE THREAD

**Issue by AntBezr** [BCH-Wunder-Project-team-4/Wunder.io#43]
This little icon 
![Screenshot 2023-12-14 at 10 31 42](https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/117649417/08e72ff1-b2f9-484e-b74e-fe427d52e426)

Even if there is no speaker this line is still appearing
![Screenshot 2023-12-14 at 10 32 16](https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/117649417/9f0d3e0f-3af6-41e8-9a5a-31a9b2aa98dc)

The map is not centered on the pin
And it looks a little bit bigger than you expect it to be..
![Screenshot 2023-12-14 at 10 33 20](https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/117649417/091a0ce8-5dcb-4926-9e64-934581c4b51c)

**Comment by julilan** [comment]
The issue with speakers heading and icon rendering is with an empty Speaker Information paragraph in the Event Speakers field being there by default. So the array length will be 1 even though fields are null.

I think the best solution is to fix this from Drupal by changing the default paragraph type to "None" for Event Speakers in Manage Form display settings.

<img width="716" alt="Screenshot 2023-12-14 at 11 09 55" src="https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/122397061/7d4f5789-3df9-41c6-843f-a976159b9b3c">

Now when you create a new event Event Speakers field will look like this:

<img width="586" alt="Screenshot 2023-12-14 at 11 47 57" src="https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/122397061/2b7536ad-8139-4c02-b965-5c0874c15136">

And nothing will be rendered about speakers until user adds Speaker Information paragraphs.

I also added help text to remove empty paragraphs to better combat this issue. I also made the event speaker name field required so now when the user is saving it will not let save when this paragraph has no information filled. That will prevent this issue resurfacing in the front end.

**Comment by julilan** [comment]
I will work on the map next! 🌍

**Comment by julilan** [comment]
I'm beginning to be more happy with the map. Now for event page it is more smaller and zoomed in, and also centered properly.

<img width="804" alt="Screenshot 2023-12-14 at 19 06 42" src="https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/122397061/4adc7b16-9127-42fb-95d7-497fc7d7230d">

The map center position is now taken from the first marker geocode, so for our Contact Us page map, it will center according to the geocode of the first Office content created. The office map will become more bigger and zoomed out when there is more than one office coming from Drupal.

<img width="1132" alt="Screenshot 2023-12-14 at 19 16 32" src="https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/122397061/cfa497e5-f841-4ffb-990a-6d59a8cc0ee8">

**Comment by julilan** [comment]
Fixed with #45
