### ISSUE TITLE
Search page Needs a little bit attention 

### ISSUE THREAD

**Issue by AntBezr** [BCH-Wunder-Project-team-4/Wunder.io#61]
![Screenshot 2023-12-19 at 16 06 44](https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/117649417/6185dc50-64b4-40aa-a185-5a709b355db0)
![Screenshot 2023-12-19 at 16 06 50](https://github.com/BCH-Wunder-Project-team-4/Wunder.io/assets/117649417/d0cc213b-2d66-40f9-b360-45f1b8d258d9)

**Comment by julilan** [comment]
Fixed with #64
